### ISSUE TITLE
Add class methods to add, remove, or update collection role to CollectionRole class

### ISSUE THREAD

**Issue by srallen** [zooniverse/panoptes-python-client#149]
We'll want to validate that a User with id is included as well as probably just hardcode in the options for `collaborator`, `contributor`, and `viewer`.

**Comment by adammcmaster** [comment]
I want to make sure I understand what's needed here. I'm pretty sure all we need to do is add `roles` and `links` to `CollectionRole._edit_attributes`. Then you should be able to do everything via normal creating/linking/saving/deleting without any new methods:

Adding a new role:

```python
new_role = CollectionRole()
new_role.links.collection = Collection(1234)
new_role.links.user = User(1234)
new_role.roles = ['collaborator']
new_role.save()
```

Updating a role:

```python
role = CollectionRole(1234)
role.roles = ['viewer']
role.save()
```

Removing a role:

```python
role = CollectionRole(1234)
role.delete()
```

I don't think we need to do any validation in the client, since the API will take care of that.
